[package]
name = "threshold"
version = "0.1.0"
authors = ["Dmitry Shuranov <dvshur@gmail.com>"]
edition = "2018"

[dependencies]
curve25519-dalek = "2"
digest = "0.8"
ed25519-dalek = "1.0.0-pre.3"
rand = "0.7"
